### ISSUE TITLE
0.39.4 has released(change to docker install)

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-metabase#5]
**What type of your feature request?**  

- [ ] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by tqf6** [comment]
![image](https://user-images.githubusercontent.com/83911329/122726507-a3d64780-d2a8-11eb-949d-9801bbc8bb66.png)

**Comment by tqf6** [comment]
无法显示版本号   13.89.233.253
![image](https://user-images.githubusercontent.com/83911329/122738306-7394a600-d2b4-11eb-8412-45ab63ed6b1a.png)

**Comment by qiaofeng1227** [comment]
default plugins:
```
bash-5.1# ls
bigquery.metabase-driver.jar         google.metabase-driver.jar           mongo.metabase-driver.jar            presto.metabase-driver.jar           snowflake.metabase-driver.jar        sqlite.metabase-driver.jar           vertica.metabase-driver.jar
druid.metabase-driver.jar            googleanalytics.metabase-driver.jar  oracle.metabase-driver.jar           redshift.metabase-driver.jar         sparksql.metabase-driver.jar         sqlserver.metabase-driver.jar
```

**Comment by qiaofeng1227** [comment]
Have create  issue to Metabase: https://github.com/metabase/metabase/issues/16824

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/123921808-fc4cc980-d9b9-11eb-9866-2fde5498e3ba.png)

**Comment by qiaofeng1227** [comment]
```
[root@iZj6ce283qzyocxruxot1hZ docker-metabase]# docker exec -it metabase bash
bash-5.1# ls
app            dev            home           lib64          metabase-data  opt            proc           run            srv            tmp            var
bin            etc            lib            media          mnt            plugins        root           sbin           sys            usr
bash-5.1# cd plugins/
bash-5.1# ls
bash-5.1# ls -l
total 0
````

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/123921938-1edee280-d9ba-11eb-9b5c-3580ed758c47.png)
---
---
![image](https://user-images.githubusercontent.com/43192516/123921973-256d5a00-d9ba-11eb-8a2d-528ae17a5d3b.png)

**Comment by qiaofeng1227** [comment]
```
[root@iZj6ce283qzyocxruxot1hZ plugins]# wget https://github.com/bbenzikry/metabase-neo4j-driver/releases/download/v0.0.7/neo4j.metabase-driver.jar
[root@iZj6ce283qzyocxruxot1hZ plugins]# ls
neo4j.metabase-driver.jar
```
![image](https://user-images.githubusercontent.com/43192516/123922631-d07e1380-d9ba-11eb-8917-034452aaa4b2.png)
