### ISSUE TITLE
metabase服务启停命令存在错误

### ISSUE THREAD

**Issue by GFangyu** [Websoft9/ansible-metabase#7]
## Language

- [ ] Chinese
- [ ] English

## Content error

Provide us with documentation errors, e.g spelling mistake, wrong screenshot, code syntax error.

* URL: https://support.websoft9.com/docs/metabase/zh/admin-services.html
* Description: metabase服务启停的命令存在错误
* Screenshot
![metabase](https://user-images.githubusercontent.com/53968450/126291406-1477cf5a-d8a8-48cb-81d5-68776c1f03d0.png)

## Content optimization

Provide us with content optimization, e.g easy to read, simplify the steps, step by step, precise expression.

* URL: 
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by qiaofeng1227** [comment]
Done
